config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'
  get 'relationships/unfollow_user'
  post ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

get 'tweets/browse'
  get 'profiles/show'
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :tweets do
    member do
      get 'like'
      get 'unlike'
    end
  end
  
  get ':username', to: 'profiles#show', as: :profile
  root 'tweets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord

    belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
    belongs_to :following, foreign_key: 'following_id', class_name: 'User'
    
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    acts_as_votable
    
    belongs_to :user

    scope :of_followed_users, -> (following_users) { where user_id: following_users }
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!
  
  def show
    @tweets = User.find_by(username: params[:username]).tweets.order('created_at DESC')
  end
  


  private
  def set_user
    @user = User.find_by(username: params[:username])
   end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end
   
    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end     
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def follow_user
    @user = User.find_by! username: params[:username]
    if current_user.follow @user.id
      respond_to do |format|
        format.html { redirect_to profile_path }
        format.js
      end
    end
  end


  def unfollow_user
    @user = User.find_by! username: params[:username]
    if current_user.unfollow @user.id
      respond_to do |format|
        format.html { redirect_to profile_path }
        format.js
      end
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    if user_signed_in?
      @tweets = Tweet.of_followed_users(current_user.following).order('created_at DESC') if user_signed_in?
    else
      @tweets = Tweet.all.order("created_at DESC")
    end
    @tweet = Tweet.new
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @tweet = current_user.tweets.find_by(id: params[:id])
    redirect_to tweets_path, notice: "Not Authorised to edit this tweet" if @tweet.nil?
  end

  def like
    if @tweet.liked_by current_user
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def unlike
    if @tweet.unliked_by current_user
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def browse
    @tweets = Tweet.all.order("created_at DESC")
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
    def current_user_is_following(current_user_id, followed_user_id)
        relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
        return true if relationship
      end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

      def display_likes(tweet)
        votes = tweet.votes_for.up.by_type(User)
        return list_likers(votes) if votes.size <= 1
        count_likers(votes)
      end

      def liked_tweet(tweet)
        if current_user.voted_for? tweet
            return 'fa fa-heart'
        else
            'fa fa-heart-o'
        end
      end

    
      private

      def list_likers(votes)
        usernames = []
        unless votes.blank?
          votes.voters.each do |voter|
            usernames.push(link_to voter.username)
          end
          usernames.to_sentence.html_safe + like_plural(votes)
        end
      end

      def count_likers(votes)
        vote_count = votes.size
        vote_count.to_s + ' likes'
      end

      def like_plural(votes)
        return ' like this' if votes.count > 1
        ' likes this'
      end

end

app/views/layouts/_alerts.html.erb
    	<% if flash[:notice] %>
        <div class="notification is-primary global-notification">
          <button class="delete"></button>
          <p class="notice"><%= notice %></p>
        </div>
  	  <% end %>

  	  <% if flash[:alert] %>
        <div class="notification is-danger global-notification">
          <button class="delete alert"></button>
          <p class="alert"><%= alert %></p>
        </div>
  	  <% end %>

app/views/layouts/_navbar.html.erb
  	<nav class="navbar is-info">
  	 <div class="navbar-brand">
  		<%= link_to root_path, class: "navbar-item" do %>
  			<h1 class="title is-5">TweetIt</h1>
  		<% end %>
			<div class="navbar-burger burger" data-target="navbarExample">
					<span></span>
					<span></span>
					<span></span>
  			</div>
  	 </div>

		<div id="navbarExample" class="navbar-menu">
			<div class="navbar-end">
          		<div class="navbar-item">
					<div class="field is-grouped">
						<p class="control">
							<%= link_to 'New Tweet', new_tweet_path, class: "button is-info is-inverted" %>
						</p>
						<% if user_signed_in? %>
							<p>
								<%= link_to "Browse", tweets_browse_path, class:"button is-info" %>
							</p>
							<p class="control">
								<%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
							</p>
							<p>
								<%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
							</p>
						<% else %>
							<p class="control">
								<%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
							</p>
							<p class="control">
								<%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
							</p>
						<% end %>
                    </div>
                </div>
            </div>
        </div>

  	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'custom', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body>

    <%= render 'layouts/alerts'%>

    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/profiles/follow.js.erb
$('#follow-button').attr('class', 'button is-info')
                   .text('Following')
                   .attr('href', "/<%= @user.username %>/unfollow_user")
                   .attr('id', 'unfollow-button');

app/views/profiles/show.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>	
							<strong><%= link_to @user.name, profile_path(@user.username) %></strong><br />
							<small><%= link_to @user.username, profile_path(@user.username) %></small>

							 <% if @user != current_user %>
								<% if current_user_is_following(current_user.id, @user.id ) %>
									<%= link_to 'Following', unfollow_user_path, class: 'button is-info', id: 'unfollow-button', method: :post %>
								<% else %>
									<%= link_to 'Follow', follow_user_path, class: 'button is-info', id: 'unfollow-button', method: :post %>
								<% end %>
							<% end %>
						
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Tweets</p>
						<p class="title is-6"><%= current_user.tweets.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">NA</p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">NA</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>


<% @tweets.each do |tweet| %>
<div class="box">
  	<article class="media">
  		<div class="media-left">
  			<figure class="image is-64x64">
				<%= gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name) %>
  			</figure>
  		</div>
  		<div class="media-content">
  			<div class="content">
  				<strong> <%= tweet.user.name %>  </strong><br />
  				<small> @<%= tweet.user.username %> </small><br/>
  				<p><%= tweet.tweet %></p>
				  <%= display_likes tweet %>
  			</div>

			  <% if user_signed_in? %>
			  <% if tweet.user_id == current_user.id %>
              <nav class="level">
  				<div class="level-right is-mobile">
				  	<%  if current_user.voted_for? tweet %>
						<%= link_to unlike_tweet_path(tweet.id), class: "level-item", id: "like_#{tweet.id}" do %>
  					  		<span class="icon has-text-danger"><i class="<%= liked_tweet tweet %>" aria-hidden="true"></i></span>
  						<% end %>
					<% else %>
						<%= link_to like_tweet_path(tweet.id), class: "level-item", id: "like_#{tweet.id}" do %>
  					  		<span class="icon"><i class="<%= liked_tweet tweet %>" aria-hidden="true"></i></span>
  						<% end %>
					<% end %>


  					<%= link_to tweet, class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to edit_tweet_path(tweet), class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to tweet, method: :delete, data: { confirm: "Are you sure you want to delete this tweet?" } do %>
  							<span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
  					<% end %>
  				</div>
				  <% else %>
				  	<%  if current_user.voted_for? tweet %>
						<%= link_to unlike_tweet_path(tweet.id), id: "like_#{tweet.id}" do %>
  					  		<span class="icon has-text-danger"><i class="<%= liked_tweet tweet %>" aria-hidden="true"></i></span>
  						<% end %>
					<% else %>
						<%= link_to like_tweet_path(tweet.id), id: "like_#{tweet.id}" do %>
  					  		<span class="icon"><i class="<%= liked_tweet tweet %>" aria-hidden="true"></i></span>
  						<% end %>
					<% end %>
  			</nav>
			  <% end %>
			  <% end %>
        </div>
  	</article>
  </div>
  <% end %>
  </div>
  

app/views/profiles/unfollow.js.erb
$('#unfollow-button').text('Follow')
                     .attr('class', 'button is-info')
                     .attr('href', "/<%= @user.username %>/follow_user")
                     .attr('id', 'follow-button');

app/views/relationships/follow_user.html.erb
<h1>Relationships#follow_user</h1>
<p>Find me in app/views/relationships/follow_user.html.erb</p>

app/views/relationships/unfollow_user.html.erb
<h1>Relationships#unfollow_user</h1>
<p>Find me in app/views/relationships/unfollow_user.html.erb</p>

app/views/tweets/_feed.html.erb
<div class="column is-half">
	<% if user_signed_in? %>
	<article class="media box">
		<figure class="media-left">
			<p class="image is-64x64">
				<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
			</p>
		</figure>
		<div class="media-content">
            <%= render 'form' %>
		</div>
	</article>
	<% end %>

<% @tweets.each do |tweet| %>
<div class="box">
  	<article class="media">
  		<div class="media-left">
  			<figure class="image is-64x64">
				<%= gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name) %>
  			</figure>
  		</div>
  		<div class="media-content">
  			<div class="content">
  				<strong> <%= tweet.user.name %>  </strong><br />
  				<small> @<%= tweet.user.username %> </small><br/>
  				<p><%= tweet.tweet %></p>
				  <%= display_likes tweet %>
  			</div>

			  <% if tweet.user_id == current_user.id %>
              <nav class="level">
  				<div class="level-right is-mobile">
				  	<%  if current_user.voted_for? tweet %>
						<%= link_to unlike_tweet_path(tweet.id), class: "level-item", id: "like_#{tweet.id}" do %>
  					  		<span class="icon has-text-danger"><i class="<%= liked_tweet tweet %>" aria-hidden="true"></i></span>
  						<% end %>
					<% else %>
						<%= link_to like_tweet_path(tweet.id), class: "level-item", id: "like_#{tweet.id}" do %>
  					  		<span class="icon"><i class="<%= liked_tweet tweet %>" aria-hidden="true"></i></span>
  						<% end %>
					<% end %>


  					<%= link_to tweet, class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to edit_tweet_path(tweet), class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to tweet, method: :delete, data: { confirm: "Are you sure you want to delete this tweet?" } do %>
  							<span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
  					<% end %>
  				</div>
				  <% else %>
				  	<%  if current_user.voted_for? tweet %>
						<%= link_to unlike_tweet_path(tweet.id), id: "like_#{tweet.id}" do %>
  					  		<span class="icon has-text-danger"><i class="<%= liked_tweet tweet %>" aria-hidden="true"></i></span>
  						<% end %>
					<% else %>
						<%= link_to like_tweet_path(tweet.id), id: "like_#{tweet.id}" do %>
  					  		<span class="icon"><i class="<%= liked_tweet tweet %>" aria-hidden="true"></i></span>
  						<% end %>
					<% end %>
  			</nav>
			  <% end %>
        </div>
  	</article>
  </div>
  <% end %>
  </div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :tweet, label: "tweet about it", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweet...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/tweets/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>	
							<strong><%= link_to current_user.name, profile_path(current_user.username) %></strong><br />
							<small><%= link_to current_user.username, profile_path(current_user.username) %></small>						
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Tweets</p>
						<p class="title is-6"><%= current_user.tweets.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6"><%= current_user.following.count %></p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6"><%= current_user.followers.count %></p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/tweets/_trends.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Trends</p>
		<a class="panel-block">
			Trend 1
		</a>
		<a class="panel-block">
			Trend 2
		</a>
		<a class="panel-block">
			Trend 3
		</a>
		<a class="panel-block">
			Trend 4
		</a>
		<a class="panel-block">
			Trend 5
		</a>
		<a class="panel-block">
			Trend 6
		</a>
	</nav>
</div>

app/views/tweets/browse.html.erb
<div class="column">
	<nav class="panel">
		<p class="panel-heading">Browse all Tweets</p>
	


<% @tweets.each do |tweet| %>
<div class="box">
  	<article class="media">
  		<div class="media-left">
  			<figure class="image is-64x64">
				<%= gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name) %>
  			</figure>
  		</div>
  		<div class="media-content">
  			<div class="content">
  				
				<strong><%= link_to tweet.user.name, profile_path(tweet.user.username) %></strong><br />
				<small><%= link_to tweet.user.username, profile_path(tweet.user.username) %></small>
				
  				
  				<p><%= tweet.tweet %></p>
				  <%= display_likes tweet %>
  			</div>

			  <% if user_signed_in? %>
			  <% if tweet.user_id == current_user.id %>
              <nav class="level">
  				<div class="level-right is-mobile">
				  	<%  if current_user.voted_for? tweet %>
						<%= link_to unlike_tweet_path(tweet.id), class: "level-item", id: "like_#{tweet.id}" do %>
  					  		<span class="icon has-text-danger"><i class="<%= liked_tweet tweet %>" aria-hidden="true"></i></span>
  						<% end %>
					<% else %>
						<%= link_to like_tweet_path(tweet.id), class: "level-item", id: "like_#{tweet.id}" do %>
  					  		<span class="icon"><i class="<%= liked_tweet tweet %>" aria-hidden="true"></i></span>
  						<% end %>
					<% end %>


  					<%= link_to tweet, class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to edit_tweet_path(tweet), class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to tweet, method: :delete, data: { confirm: "Are you sure you want to delete this tweet?" } do %>
  							<span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
  					<% end %>
  				</div>
				  <% else %>
				  	<%  if current_user.voted_for? tweet %>
						<%= link_to unlike_tweet_path(tweet.id), id: "like_#{tweet.id}" do %>
  					  		<span class="icon has-text-danger"><i class="<%= liked_tweet tweet %>" aria-hidden="true"></i></span>
  						<% end %>
					<% else %>
						<%= link_to like_tweet_path(tweet.id), id: "like_#{tweet.id}" do %>
  					  		<span class="icon"><i class="<%= liked_tweet tweet %>" aria-hidden="true"></i></span>
  						<% end %>
					<% end %>
  			</nav>
			  <% end %>
			  <% end %>
        </div>
  	</article>
  </div>
  <% end %>
  </div>
  

app/views/tweets/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing tweet</h1>
				<%= render 'form', tweet: @tweet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
        <% if user_signed_in? %>
          <%= render 'tweets/profile' %>
        <% else %>
          <%= render 'tweets/trends' %>
        <% end %>
       <%= render 'tweets/feed' %>
    </div>
  </div>
</section>

app/views/tweets/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new tweet</h1>
					<%= render 'form', tweet: @tweet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>